# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  apiservice:
    image: apiservice
    build:
      context: .
      dockerfile: ApiService/Dockerfile
    ports:
      - 4000:4000
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
